// Package mobile exposes the relay proxy for gomobile binding.
package mobile

import (
	"zyrln/relay/core"
	"fmt"
	"net/http"
	"strings"
	"sync"
	"time"
)

const (
	defaultFrontDomain = "www.google.com"
	defaultTimeout     = 45 * time.Second
)

var (
	mu        sync.Mutex
	server    *http.Server
	lastErr   string
)

// Start starts the HTTPS MITM relay proxy on listenAddr (e.g. "127.0.0.1:8085").
// appScriptURL may be a single URL or a comma-separated list of URLs tried in order.
// caCertPath and caKeyPath must point to an existing CA generated by GenerateCA.
// Returns an error string, or "" on success.
func Start(appScriptURL, authKey, listenAddr, caCertPath, caKeyPath string) string {
	mu.Lock()
	defer mu.Unlock()

	if server != nil {
		return ""
	}

	ca, err := core.LoadCA(caCertPath, caKeyPath)
	if err != nil {
		lastErr = fmt.Sprintf("load CA: %s", err)
		return lastErr
	}

	client := core.NewHTTPClient(defaultTimeout)
	urls := parseURLList(appScriptURL)

	srv, err := core.StartProxy(listenAddr, urls, defaultFrontDomain, authKey, ca, client, defaultTimeout)
	if err != nil {
		lastErr = err.Error()
		return lastErr
	}

	server = srv
	lastErr = ""
	return ""
}

func parseURLList(raw string) []string {
	parts := strings.Split(raw, ",")
	out := make([]string, 0, len(parts))
	for _, p := range parts {
		u := strings.Map(func(r rune) rune {
			if r == ' ' || r == '\n' || r == '\r' || r == '\t' {
				return -1
			}
			return r
		}, p)
		if u != "" {
			out = append(out, u)
		}
	}
	return out
}

// Stop shuts down the relay proxy.
func Stop() {
	mu.Lock()
	defer mu.Unlock()
	if server != nil {
		_ = server.Close()
		server = nil
	}
}

// IsRunning returns true if the proxy is currently running.
func IsRunning() bool {
	mu.Lock()
	defer mu.Unlock()
	return server != nil
}

// LastError returns the last error from Start, or "" if none.
func LastError() string {
	mu.Lock()
	defer mu.Unlock()
	return lastErr
}

// GenerateCA generates a local CA cert + key at the given paths.
// Returns an error string, or "" on success.
func GenerateCA(certPath, keyPath string) string {
	if err := core.GenerateCA(certPath, keyPath); err != nil {
		return err.Error()
	}
	return ""
}
